COMMON: &common
  SECRET_KEY: '47e585de7f22984d5ee291c2f31412384bfc32d0'
  SECURITY_POST_LOGIN_VIEW: '/profile'

  SECURITY_TRACKABLE: True
  SOCIAL_CONNECT_ALLOW_VIEW: '/profile'

  SOCIAL_TWITTER:
    consumer_key: 'key'
    consumer_secret: 'secret'

  SOCIAL_FACEBOOK:
    consumer_key: '562264433940447'
    consumer_secret: 'b54df4c22dff59c704168ff26ad1884d'
    request_token_params:
      scope: 'email,publish_stream'

  SOCIAL_GITHUB:
    consumer_key: 'key'
    consumer_secret: 'secret'
    module: 'app.github'

  UPLOAD_FOLDER: '/imageUploads'
  ALLOWED_EXTENSIONS:
    - 'png'
    - 'jpg'
    - 'jpeg'
    - 'gif'

  WEIGHINDAY: 1

  SECURITY_PASSWORD_HASH: 'plaintext'
  SECURITY_EMAIL_SENDER: 'healthymamaschallenge@gmail.com'
  SECURITY_CONFIRMABLE: True
  SECURITY_REGISTERABLE: True
  SECURITY_RECOVERABLE: True
  SECURITY_CHANGEABLE: True

  SECURITY_CONFIRM_SALT: '570be5f24e690ce5af208244f3e539a93b6e4f05'
  SECURITY_REMEMBER_SALT: 'de154140385c591ea771dcb3b33f374383e6ea47'
  SECURITY_DEFAULT_REMEMBER_ME: True

  # Set secret keys for CSRF protection
  CSRF_SESSION_KEY: '8a7474974efcf76896aa84eea9cbe016bbc08828'
  CSRF_ENABLED: True

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: mysql+pymysql://website:N0thing!@localhost/WeightLoss
  ADMIN_CREDENTIALS: 'root,nothing'

PRODUCTION: &production
  <<: *common
  DEBUG: False
  SQLALCHEMY_DATABASE_URI: mysql+pymysql://website:N0thing!@localhost/WeightLoss
  ADMIN_CREDENTIALS: 'root,nothing'
  SECURITY_PASSWORD_HASH: bcrypt
  SOCIAL_APP_URL: http://90day.noeltanis.com/
